version: '3'

services:
  php:
    container_name: php
    user: 1000:1000
    image: php:8.0.3-fpm-alpine
    env_file: ../../.env
    volumes:
      - ../..:/var/www/app
    expose:
      - 9000
    networks:
      - default

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    volumes:
      - ../..:/var/www/app:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    networks:
      - default

networks:
  default:
    driver: bridge
