version: '3'

services:
  php:
    container_name: php
    user: 1000:1000
    build: .
    env_file: ../../.env
    environment:
      - PHP_IDE_CONFIG=serverName=Docker
    volumes:
      - ../..:/var/www/app
    working_dir: /var/www/app
    expose:
      - 9000
    networks:
      - default

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    volumes:
      - ../..:/var/www/app:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    networks:
      - default

networks:
  default:
    driver: bridge
