static:
  resource: ../../src/Infrastructure/Static/RequestHandler.php
  type: annotation
  prefix: /
  name_prefix: static_

api:
  resource: ../../src/Infrastructure/IncomeCalculator/RequestHandler.php
  type: annotation
