static:
  resource: ../../src/Infrastructure/Static/RequestHandler.php
  type: annotation
  prefix: /
  name_prefix: static_

api_income_calculator:
  resource: ../../src/Infrastructure/IncomeCalculator/RequestHandler.php
  type: annotation

api_spend_calculator:
  resource: ../../src/Infrastructure/SpendCalculator/RequestHandler.php
  type: annotation
