parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/Kernel.php'
      - '../src/Core/IncomeCalculator/{Exception,Model}'
      - '../src/Core/SpendCalculator/{Exception,Model}'

  App\Core\IncomeCalculator\Service:
    arguments:
      $strategies:
        - '@App\Core\IncomeCalculator\CalculateStrategy\RegularPayment'
        - '@App\Core\IncomeCalculator\CalculateStrategy\FinalAmountWithRegularPayments'
        - '@App\Core\IncomeCalculator\CalculateStrategy\FinalAmountWithoutRegularPayments'
        - '@App\Core\IncomeCalculator\CalculateStrategy\NumberOfYearsWithRegularPayments'
        - '@App\Core\IncomeCalculator\CalculateStrategy\NumberOfYearsWithoutRegularPayments'
        - '@App\Core\IncomeCalculator\CalculateStrategy\InterestRatePerYearWithRegularPayments'
        - '@App\Core\IncomeCalculator\CalculateStrategy\InterestRatePerYearWithoutRegularPayments'
        - '@App\Core\IncomeCalculator\CalculateStrategy\InitialAmountWithRegularPayments'
        - '@App\Core\IncomeCalculator\CalculateStrategy\InitialAmountWithoutRegularPayments'

  App\Core\SpendCalculator\Service:
    arguments:
      $strategies:
        - '@App\Core\SpendCalculator\CalculateStrategy\InitialAmount'
        - '@App\Core\SpendCalculator\CalculateStrategy\FinalAmount'
        - '@App\Core\SpendCalculator\CalculateStrategy\PaymentAmount'
        - '@App\Core\SpendCalculator\CalculateStrategy\NumberOfYears'
        - '@App\Core\SpendCalculator\CalculateStrategy\InterestRatePerYear'
